---
- name: fqdn | Check for FQDN variable presence
  fail:
    msg: "FQDN variable is not set!"
  when: fqdn|default(False) == False

- name: fqdn | Check for hostname variable presence
  fail:
    msg: "Hostname variable is not set!"
  when: hostname|default(False) == False

- name: fqdn | Configure Debian
  include: debian.yml
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]

- name: fqdn | Configure Redhat
  include: redhat.yml
  when: ansible_distribution in [ 'RedHat', 'CentOS' ]

- name: fqdn | Configure Suse versions older than 12
  include: old_suse.yml
  when: ansible_os_family == "Suse" and ansible_distribution_major_version <= 11

- name: fqdn | Configure Linux
  include: linux.yml
  when: ansible_system in  [ "Linux" ]

- name: fqdn | Configure Windows
  include: windows.yml
  when: ansible_system in  [ "Win32NT" ]
